$(document).ready(function(){
    $(".dor").click(function(){
        $("#im").toggle();
        $("#pa").toggle();
    });
    $(".doru").click(function(){
        $("#am").toggle();
        $("#par").toggle();
    });
    $(".koe").click(function(){
        $("#las").toggle();
        $("#the").toggle();
    });
});